### ISSUE TITLE
MEM dump notworking

### ISSUE THREAD

**Issue by zer0visua1** [OMENScan/AChoir#5]
The latest update broke memdump

SET: Creating Acquisition Sub-Directory: MemDump
SET: Acquisition Sub-Directory Has Been Set To: MemDump
[!] Program Not Found

Replacing the 'MEM' folder from a previous version and it fixed the issue.
  Also, like you recommended in the README, run the AChoir builder and it works like it should (MEM folder is there).

**Comment by OMENScan** [comment]
The second part of AChoir's Install downloads several other FOSS utilities.  This is done by simply running AChoir with the Build.ACQ script (/INI:Build.ACQ).

The /MEM directory is created by this script by downloading WinPmem from the Rekall Github Repo:

SAY: --- Getting WinPMem 1.6.2 (from GitHub/Rekall) ---
SAY:
DIR:\MEM
FIL:WinPmem201.exe
EXE:\cURL.exe -L -s -k -o &Dir\&Fil -D &Dir\WinPMem201.txt https://github.com/google/rekall/releases/download/v1.3.2/winpmem_2.0.1.exe
Fil:WinPmem.exe
EXE:\cURL.exe -L -s -k -o &Dir\&Fil -D &Dir\WinPMem.txt https://github.com/google/rekall/releases/download/v1.3.1/winpmem_1.6.2.exe
SAY:

What likely happened is that AChoir could not download WinPmem due to a network error.  Rerunning the build script (AChoir /BLD) would fix the problem by rerunning the Build.ACQ script.  

Or just copying the /MEM directory from an older install would work just as well.
